### ISSUE TITLE
Error in ./upgradeCC.sh 0.2 2 -n 1, from 1 org, after ./startDev.sh -n 1.

### ISSUE THREAD

**Issue by matheusLazaroCC-UFG** [hyperledger-labs/cc-tools-demo#68]
Attached are the steps that indicate an error in ./upgradeCC.sh 0.2 2 -n 1, from 1 org, after ./startDev.sh -n 1.

**Docker cleanup and start**
![Captura de tela de 2024-07-07 19-12-51](https://github.com/hyperledger-labs/cc-tools-demo/assets/71093772/86fda288-3c9a-42d6-978d-421b52c88e74)

![Captura de tela de 2024-07-07 19-26-27](https://github.com/hyperledger-labs/cc-tools-demo/assets/71093772/881c9ef8-8e03-4568-a22e-5d21b34abde1)

**docker ps**
![Captura de tela de 2024-07-07 19-26-53](https://github.com/hyperledger-labs/cc-tools-demo/assets/71093772/762c3824-f0ee-4bee-a94b-1e972784fc48)

**error pointed out**:
![Captura de tela de 2024-07-07 19-30-15](https://github.com/hyperledger-labs/cc-tools-demo/assets/71093772/c1f25f5c-7c2d-4d32-be13-7f71cd6d7b2b)

**Comment by samuelvenzi** [comment]
Fixed on #69
